logger:
  level: "DEBUG"
  
# runtime:
#   path: "./data/modules"
#   env:
#     - key: "GOMAXPROCS"
#       value: "4"
#   grpc_headers_max_size: 10485760
#   grpc_max_concurrent_streams: 1024
#   grpc_max_connection_idle_ms: 15000
#   grpc_max_connection_age_ms: 1800000
#   grpc_max_connection_age_grace_ms: 5000
#   grpc_max_message_size: 4194304
#   grpc_max_recv_msg_size: 4194304
#   grpc_max_send_msg_size: 4194304
#   module:
#     - "./data/modules/backend.so"
